version: '3'
services:
  web:
    build: .
    command: rails s -b 0.0.0.0
    volumes:
      - .:/var/www/ingresse_dev_test
    ports:
      - 80:3000
    environment:
    - "VIRTUAL_HOST=api.ingressdev.test"
volumes:
  ingresse_dev_test-data:
